### ISSUE TITLE
Svg format support

### ISSUE THREAD

**Issue by Kidav** [gplessis/dotdeb-php-imagick#2]
It would be nice if module will support svg format. For now when I try to convert svg to png next error appers:

Uncaught ImagickException: no decode delegate for this image format SVG

**Comment by gplessis** [comment]
@Kidav : could you please check that the `libmagickcore-6.q16-2-extra` package is installed on your machine first. It bring SVG support to MagickCore and any linked software.

Thanks for letting me know if it solves your issue.

**Comment by Kidav** [comment]
Yes, you are right. Thank you so much. This package brings svg support
